title: GitHub Pages Course
description: Learn to create a site or blog from your GitHub repositories with GitHub Pages
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/

# Collections
collections:
  steps:
    output: true
    permalink: /:collection/:name/ 